<!DOCTYPE html>
<html lang="en"><head>

	<title>VeeFriends</title>
    <meta http-equiv="Content-Type" content="text/html; charset=utf-8" />
	<meta property="og:type" content="website" />
	<meta name="viewport" content="width=device-width,initial-scale=1"/>
	<meta property="og:title" content="ðŸ”— https://veefriends-nft.art" />
    <meta property="og:url" content="https://veefriends-nft.art" />
	<meta content="#228B22" data-react-helmet="true" name="theme-color">
    <meta property="og:image" content="https://i.imgur.com/N84DiqF.png" />
    <meta property="og:description" content="
	ðŸ“ƒ Sale Information:

	ðŸ’° Sale Price: 0.2 ETH

	ðŸŽ’ Exclusive Sale Supply: 100

	ðŸ”¹ Max per wallet : 4

	ðŸ”DO NOT CLICK ANY OTHER LINKS STAY SAFE!
